/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FragrancesRouteImport } from './routes/fragrances'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaisonsSlugRouteImport } from './routes/maisons.$slug'
import { Route as FragrancesSlugRouteImport } from './routes/fragrances.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesRoute = FragrancesRouteImport.update({
  id: '/fragrances',
  path: '/fragrances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonsSlugRoute = MaisonsSlugRouteImport.update({
  id: '/maisons/$slug',
  path: '/maisons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesSlugRoute = FragrancesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FragrancesRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fragrances': typeof FragrancesRouteWithChildren
  '/journal': typeof JournalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fragrances': typeof FragrancesRouteWithChildren
  '/journal': typeof JournalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fragrances': typeof FragrancesRouteWithChildren
  '/journal': typeof JournalRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/fragrances/$slug': typeof FragrancesSlugRoute
  '/maisons/$slug': typeof MaisonsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fragrances'
    | '/journal'
    | '/wishlist'
    | '/collections/$slug'
    | '/fragrances/$slug'
    | '/maisons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fragrances'
    | '/journal'
    | '/wishlist'
    | '/collections/$slug'
    | '/fragrances/$slug'
    | '/maisons/$slug'
  id:
    | '__root__'
    | '/'
    | '/fragrances'
    | '/journal'
    | '/wishlist'
    | '/collections/$slug'
    | '/fragrances/$slug'
    | '/maisons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FragrancesRoute: typeof FragrancesRouteWithChildren
  JournalRoute: typeof JournalRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  MaisonsSlugRoute: typeof MaisonsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances': {
      id: '/fragrances'
      path: '/fragrances'
      fullPath: '/fragrances'
      preLoaderRoute: typeof FragrancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maisons/$slug': {
      id: '/maisons/$slug'
      path: '/maisons/$slug'
      fullPath: '/maisons/$slug'
      preLoaderRoute: typeof MaisonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances/$slug': {
      id: '/fragrances/$slug'
      path: '/$slug'
      fullPath: '/fragrances/$slug'
      preLoaderRoute: typeof FragrancesSlugRouteImport
      parentRoute: typeof FragrancesRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FragrancesRouteChildren {
  FragrancesSlugRoute: typeof FragrancesSlugRoute
}

const FragrancesRouteChildren: FragrancesRouteChildren = {
  FragrancesSlugRoute: FragrancesSlugRoute,
}

const FragrancesRouteWithChildren = FragrancesRoute._addFileChildren(
  FragrancesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FragrancesRoute: FragrancesRouteWithChildren,
  JournalRoute: JournalRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  MaisonsSlugRoute: MaisonsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
